name: Diwali wishes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Next.js Application to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 13.201.167.137
          username: ubuntu
          key: ${{ secrets.PVT_SECRET }}
          port: 22
          script: whoami